### PR TITLE
Fix TA build errors in aosp

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by etienne-lms** [comment]
Thanks. I have merge this in the commit since there few many issues.
Could you recall me which **gcc** you use useless its some specific `-Werror`?
It would be nice for me to catch them also in my builds.

**Comment by vchong** [comment]
Np. Sorry but where did you merge this exactly?
The gcc I use is in https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+/master/bin, but I think it'll only work in an aosp build env. I think you might be able to use http://releases.linaro.org/components/toolchain/binaries/4.9-2017.01/aarch64-linux-gnu/gcc-linaro-4.9.4-2017.01-x86_64_aarch64-linux-gnu.tar.xz to catch similar errors.

**Comment by etienne-lms** [comment]
Thanks, i'll try.

> Sorry but where did you merge this exactly?

It is no visible yet. I still have malloc leakage somewhere. I want to tackle it before merging. I've checked back the current 'sks' branches with some endurance looping test and it is find. I don't want to introduce such regression as quite painful to locate.
Have a look a the branch 'sks-find' i've just pushed. It gives you my latest state.

**Comment by vchong** [comment]
Ok thanks! I'll use 'sks-find' for now. Please keep me posted.

**Comment by etienne-lms** [comment]
Ok, i should use P-Rs on my github so you can get visibility on on-going changes. I will for now.

**Comment by etienne-lms** [comment]
merged in https://github.com/etienne-lms/optee_os/pull/5

**Pull request closed without merging**
