### PR TITLE
sks ta: find objects

### PR DESCRIPTION
**Pull request by etienne-lms**
3 invocation commands: SKS_CMD_FIND_OBJECTS*. A command initializes
a search and establishes list of matching objects. A command allows
client to get handles (by burst) for matching objects. Last command
finalize the search and releases the search resources. When the
session closes (whatever reason) the search resource must be released.

The object search resources are referenced by a "find object" context
structure. It stores all allocated resources: the target matching
attributes list, a list of object handles for the client and a list
of persistent objects that matched the search but have not yet registered
through a handle within the session.

### CODE REVIEW

**Comment by etienne-lms** [comment]
This change introduces a malloc leakage regression. Need to be fixed before merging.

**Comment by etienne-lms** [comment]
seems ok. issue not reproduced.
@vchong, i've merged this.

**Comment by vchong** [comment]
@etienne-lms Thanks! So will you merge this eventually into `sks-next` branch? Or should i just keep using `sks-find` branch?

**Comment by etienne-lms** [comment]
The right branch to track is the "sks" branch.
All my other branches are temporary branches.
From now on, I will not force push the "sks" branch (rebase), but rather merge the original optee_os to resync with.

**Comment by etienne-lms** [comment]
Note "sks" branch is also the one you should track in https://github.com/etienne-lms/optee_client and  https://github.com/etienne-lms/optee_test.

**Comment by vchong** [comment]
Ok. I was using `sks-next` for all 3. I'll change them back to `sks`. Thanks!

**Pull request merged**
